- hosts: master
  gather_facts: False
  connection: local
  become: yes
  tasks:  # DNF
    - name: comprobar actualización discord
      ansible.builtin.dnf5:
        pkg:
          - discord
        state: latest
        update_cache: yes
